### ISSUE TITLE
How is the g(X) in Formula 2 implemented in the paper

### ISSUE THREAD

**Issue by MrTuo** [dmis-lab/position-bias#2]
Hello, I am trying to use your debias method(Learned-Mixin) in your parer. I found that g(X) is a kind of affine transformation. I'm trying to find the implemention in your code but i didn't find it. Is that just a simple feedforward neural network? Can you give me a formula of g(X)? Thanks a lot!

**Comment by miyoungko** [comment]
Hi, I'm sorry that I missed all issues made in this year. 
Although it is very late, the answer is that it is a simple linear layer as below. (You can find it in modeling_bert.py file)
`        self.mixin = nn.Linear(config.hidden_size, 1, bias=False)`
